---
- name: Deploy Scientific Calculator
  hosts: localhost
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "saki2726/scientific-calculator"
        source: pull

    - name: Stop existing container
      command: docker stop scientific-calculator
      ignore_errors: yes

    - name: Remove existing container
      command: docker rm scientific-calculator
      ignore_errors: yes

    - name: Run Docker Container
      shell: docker run -it -d --name calculator saki2726/scientific-calculator
